language: node_js

node_js:
  - stable
  - '8'
  - '6'

sudo: false

env:
  global:
    secure: hPSuklbeoCEX6DwrFyGGMIiQVW8+jLxHnT3sjNfhWszk5xryCr8lKjxY9GPoHqqOrKcXlVg7JyAiSB6O3r0CXof6Zj21i+L5cyBecVUgdTdN5S75clNW3r3oAALp4djQie/GhVm5a0KAag3yoGmgHBiUusWf81D99cwrXzsmj443MTy6jWlEtgR5anGw0aJD4IRSnf7Jfr4Ms2GUQdSmawgw+iScRXz0svNF3TANrc7OoHBLxlvHo1nBDZW+h1jPVQPCdq4599uReNGfIMso+VmBVYpWsuvCtmKr1vY3tWL4elpzbzGII+wmDk61QX+Rpfclmej0vPI+yWd1WAKpt4ZN5rh0GLw7/H6BM3RYeXUg1Vz+VzgTx+/3VKz9y8l7/QspWn9+5yn38NdUBx57/sleX6vlOfeHNgxCXF42THbgoA21Ek4LkUjBfIdpEGNtdl66qZgPg0dwfKikKzI5MjjtLZrPprsZgl95/JBqLX6ygH0pCayAXrYpOgU5vd2K+/ABMZQpuuPKjAz3AZDnTQuaW6rsR0pRB7Y24e1xAWf2rDV71ZkTvQ6Pr9dy8w4O+xjUzrW407iuyhAquPEBSsseMoIaa7tE/EsvTSu1S0pajlw8QQpoyptQujyOGTsLfZ1U0wNV55xNfVE0WiblDGDvruhHqUyZEVt3PDhvRFI=

before_install:
  - npm install -g pr-bumper@^3.0.0

install:
  - yarn install

before_script:
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh

deploy:
  provider: npm
  email: dogmaiobot@gmail.com
  skip_cleanup: true
  on:
    all_branches: true
    node: '8'
    tags: true
  api_key:
    secure: 1tvzoUM+X3xMrz5BNPbu6ZLppA/jXJMAn2aNg1rWZ4qtTF0MTH3vHOzOqLg+lnZiXWodvN0RiYipdJZbdVtMvPf+wqrghgn86AoKpo9gLeL/df4FG+woi+G22hDxvJw85VP4xZ9SVmSVgXUoGhvzJVg7SB1w5AGCJszPDJifbViuvBa0EMISOPy2HZ1C5g2qbYMx28yFWGVr6nZS25/7gZw7E4n9cDM4D2p5SUlJowizVGybRnsSr1M13JPLH0Bv7bRMOpIx9wioO9LnfYDjP0AEWQItHaQJrF8aZ7x2pL74KedughkVkt5Yngzi4E0aZenfOmTxbpBNxQqzsryjfssUbzYnEa6vVMhtDzsnqgIMUVRsBEWj8NQGOikZGYeTSdKNbtdQgj03fpwJRY61CdcdmKHZ0Tkqwxb2RSp4uMptJDaPpB+PWE83lwp+SevHgC9dMCYGMRG0a0qD35BO/JRSN5HL56WW38k6zku+6hcn7TLzJiPKQ1HpkJwlNl+fk/yGrmTJAHU7wjOW4iRLY4o4TQI/wWIHUpg89exE7SBhvaOWninDGP+aNurgwKdpIRLB+iV8lcaLba2M+GvyINEX9NOlzb12rgJ843OiZFJUrc5LVFGIMHpqVTpXq/Q9XIoQ8v+qvS8R/LzweWEyBa/+eOiCAP+4P44hC/oEVk4=
