language: node_js

node_js:
  - stable
  - '8'
  - '6'

sudo: false

before_install:
  - npm install -g pr-bumper@^3.0.0

install:
  - $(npm root -g)/pr-bumper/.travis/maybe-install.sh

before_script:
  - $(npm root -g)/pr-bumper/.travis/maybe-check-scope.sh

script:
  - $(npm root -g)/pr-bumper/.travis/maybe-test.sh
  - $(npm root -g)/pr-bumper/.travis/maybe-bump-version.sh

deploy:
  provider: npm
  email: dogmaiobot@gmail.com
  skip_cleanup: true
  on:
    all_branches: true
    node: '8'
    tags: true
